spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/spotify_data
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  main:
    web-application-type: servlet
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true

  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/spotify"
            authorization-grant-type: authorization_code
            scope:
              - playlist-read-private
              - playlist-modify-private
              - playlist-read-collaborative
              - user-library-read
              - user-library-modify
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id